import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { api, getBaseUrl } from "./api";

import {
  formatDate,
  formatDateTime,
  parseDate,
  parseDateTime,
  formatTime,
  batchCurrentStep,
  generateForgotStepBatchUpdateData,
  mapRouteFromStep,
  convertDairyToForm,
  convertDairyFromForm,
  convertEmployeesFromTable,
  convertEmployeesToTable,
  convertDairyCheeseTypesToTable,
  convertToDairyCheeseTypesFromForm,
  convertDairyFromCreateForm,
  convertCheeseTypeFromCreatePage,
  convertCheeseTypeToPage,
  convertCheeseTypeFromPage,
  serializableBatchWithDairy,
  serializableDairy,
  serializableDairyCheeseType,
  parseBatchDatesToDate,
  formatToStringTime,
  formatToTimeRange,
} from "./helpers";

const cn = (...inputs: ClassValue[]) => twMerge(clsx(inputs));
export {
  cn,
  api,
  getBaseUrl,
  formatDate,
  parseDate,
  formatTime,
  formatDateTime,
  parseDateTime,
  batchCurrentStep,
  generateForgotStepBatchUpdateData,
  mapRouteFromStep,
  convertDairyToForm,
  convertDairyFromForm,
  convertEmployeesFromTable,
  convertEmployeesToTable,
  convertDairyCheeseTypesToTable,
  convertToDairyCheeseTypesFromForm,
  convertDairyFromCreateForm,
  convertCheeseTypeFromCreatePage,
  convertCheeseTypeToPage,
  convertCheeseTypeFromPage,
  serializableBatchWithDairy,
  serializableDairy,
  serializableDairyCheeseType,
  parseBatchDatesToDate,
  formatToStringTime,
  formatToTimeRange,
};
